version: "3.8"
services:
  backoffice:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "4200:4200"
    volumes:
      - ./src:/app/src
      - node_modules:/app/node_modules

volumes:
  node_modules:
